### ISSUE TITLE
Use `gitzy` with `prepare-commit-msg`

### ISSUE THREAD

**Issue by fmal** [jimmy-guzman/gitzy#511]
### Describe the feature you'd like:

Hi, i tried to setup gitzy so you can interact with it on every `git commit` command.

With `lefthook` i specified the following:

```yml
prepare-commit-msg:
  commands:
    gitzy:
      interactive: true
      run: yarn gitzy
      env:
        LEFTHOOK: 0

commit-msg:
  commands:
    commitlint:
      run: yarn commitlint --edit {1}
```

It sort of works, i can interact with gitzy when typing `git commit` but after running `gitzy` text editor opens and prompt for a message. Also the following error is logged to the console:

<img width="853" alt="SCR-20250110-bmas" src="https://github.com/user-attachments/assets/31bc06cb-8629-47d5-8f06-41689ff6cc57" />

### Suggested implementation:

With https://github.com/commitizen/cz-cli it's possible to pass `--hooks` flag designed for running inside hooks: https://github.com/commitizen/cz-cli?tab=readme-ov-file#optional-running-commitizen-on-git-commit.

When enabled the commit message is written directly to `.git/COMMIT_EDITMSG` file as far as i can see: https://github.com/commitizen/cz-cli/blob/master/src/git/commit.js#L52

### Describe alternatives you've considered:

Is this something that you have considered supporting? Or maybe it's already possible to run `gitzy` on git commit, but i'm missing something in my setup? 

Thanks and really nice tool btw ❤️
