### ISSUE TITLE
containerize `gitzy`

### ISSUE THREAD

**Issue by jimmy-guzman** [jimmy-guzman/gitzy#6]
### Describe the feature you'd like:
Would like to a see a docker container that allows to users to do something like:
```yml
version: '3.8'
services:
  gitzy:
    image: gitzy
    stdin_open: true
    tty: true
    volumes:
      - ~/.gitconfig:/etc/gitconfig
      - ./:/app
``` 

```sh-session
$ docker-compose run gitzy --commitlint
```

That way it can be used in any environment. 
      
### Suggested implementation:
Can probably be as simple as 
```docker
FROM node:14.15.4-alpine

RUN apk --no-cache add git && rm -rf /var/cache/apk/*

COPY . /app
WORKDIR /app

ENTRYPOINT ["./bin/run"]
```
